---
title: "Coats analysis writeup [Readme]"
author: "Meng Le Zhang"
date: "14 June 2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Introduction

This is a markdown file detailing how the analysis of the Coats data was done. The
coats data focuses on clerks between 1889 and 1930 at the firm. Female clerks
starting appearing in the firm during the first world war. 

##  Data
Tenure is measured by the number of years that an individual had previously worked at Coats and this was mainly estimated using their previous appearances in the salary books. This includes years where an individual was transferred out of the Glasgow office but still remained with Coats. Furthermore, men enlisted during the war still had their military service count towards their tenure at Coats (assuming they returned to Coats). If the recorded year of commencement of employment at Coats was prior to the first year a clerk appears in the salary book then took that as the starting date for calculating tenure.  
When an individual left the company (e.g. during the war) and rejoined, their tenure continued from their last employment at Coats.   In some cases, the exact year a person commenced working at Coats is recorded. In a minority of these cases, recorded year of commencement was before their first recorded year of service. This is likely due to missing salary books and for these individuals their tenure is based on their year of commencement. As a robustness check, we excluded these cases from the analysis and found that they did not affect the substantive results. Since female clerks did not appear in great numbers until after 1900, we have restricted our analysis of their wages to the period 1901 – 1930. Furthermore, we conducted separate analyses for men and women.
